/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Train Booking System Running Successfully ");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("Error occured while reading user booking data");
            return;
        }

        while(option != 7){
            System.out.println("Please enter your option");
            System.out.println("1 - Sign Up");
            System.out.println("2 - Login");
            System.out.println("3 - Fetch Bookings");
            System.out.println("4 - Search Trains");
            System.out.println("5 - Book a Seat");
            System.out.println("6 - Cancel Booking");
            System.out.println("7 - Exit App");
            option = scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Please enter your Name:");
                    String nameSignup = scanner.next();

                    System.out.println("Please enter your Password:");
                    String passwordSignup = scanner.next();

                    User userToSignup = new User(nameSignup, passwordSignup, UserServiceUtil.hashPassword(passwordSignup), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;

                case 2:
                    System.out.println("Please enter your Name:");
                    String nameSignin = scanner.next();
                    System.out.println("Please enter your Password:");
                    String passwordSignin = scanner.next();
                    User userToLogin = new User(nameSignin, passwordSignin, UserServiceUtil.hashPassword(passwordSignin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException e) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching Bookings");
                    userBookingService.fetchBooking();
                    break;
            }
        }
    }
}
